DEV: Added postProcess.py Automatically create images for verification

diff --git a/validation/blastFoam/2D_Riemann/Allrun b/validation/blastFoam/2D_Riemann/Allrun
--- a/validation/blastFoam/2D_Riemann/Allrun
+++ b/validation/blastFoam/2D_Riemann/Allrun
@@ -1,26 +1,33 @@
-#!/bin/sh
+#!/bin/bash -i
 cd ${0%/*} || exit 1    # run from this directory
 
-# Source tutorial run functions
-. $WM_PROJECT_DIR/bin/tools/RunFunctions
-
-# -- Create paraview file
-paraFoam -builtin -touch
-
-# -- Create mesh
-runApplication blockMesh
-
-# -- Decompose the case
-runApplication decomposePar
-
-# -- Add internal patch
-runParallel addEmptyPatch internalPatch internal -overwrite
-
-# -- Set initial conditions
-runParallel setRefinedFields
-
-# -- run the calc
-runParallel $(getApplication)
-
+# source ~/.bashrc
+#
+# # Source tutorial run functions
+# . $WM_PROJECT_DIR/bin/tools/RunFunctions
+#
+# # -- Create paraview file
+# paraFoam -builtin -touch
+#
+# # -- Create mesh
+# runApplication blockMesh
+#
+# # -- Decompose the case
+# runApplication decomposePar
+#
+# # -- Add internal patch
+# runParallel addEmptyPatch internalPatch internal -overwrite
+#
+# # -- Set initial conditions
+# runParallel setRefinedFields
+#
+# # -- run the calc
+# runParallel $(getApplication)
+if ! command -v pvpython >/dev/null 2>&1
+then
+    echo "pvpython could not be found, no creating images"
+else
+    pvpython postProcess.py
+fi
 
 # ----------------------------------------------------------------- end-of-file
